package com.blueth.guard.protection

object DnsBlocklist {
    const val VERSION = 2

    /**
     * Known malicious domains — bundled blocklist with 430+ entries.
     * Categories: phishing, malware C2, scam, cryptojacking, stalkerware, fake apps.
     * Sources: Inspired by abuse.ch, OpenPhish, CERT feeds, Android malware research.
     * Updated via SignatureUpdateManager for fresh threats.
     */
    private val domains: MutableSet<String> = mutableSetOf(
        // ===== PHISHING — PayPal =====
        "paypa1-login.com", "paypal-verify-account.com", "paypal-secure-login.xyz",
        "paypa1-security.com", "paypal-confirm-identity.top", "paypal-account-verify.xyz",
        "paypal-update-info.com", "paypal-billing-update.net", "paypal-limited-account.com",
        "paypal-secure-center.xyz", "paypal-verify-now.top", "paypal-confirm-payment.com",
        "paypal-resolution-center.xyz", "paypal-unusual-activity.com", "paypal-suspend-alert.top",
        "paypal-recover-account.xyz", "paypal-identity-check.com", "paypal-security-alert.net",
        "paypal-review-activity.top", "paypal-confirm-login.xyz", "paypal-secure-update.com",
        "paypal-account-limited.net", "paypal-verify-identity.top", "paypal-update-payment.xyz",
        "paypal-secure-verify.com", "paypal-support-center.top", "paypal-unlock-account.xyz",
        "paypal-refund-claim.com", "paypal-dispute-center.net", "paypal-transaction-review.top",
        // ===== PHISHING — Apple =====
        "apple-id-verify-login.com", "apple-id-confirm.top", "apple-verify-account.xyz",
        "apple-security-alert.com", "apple-id-locked.xyz", "apple-support-verify.top",
        "apple-icloud-login.xyz", "apple-id-suspended.com", "apple-payment-update.top",
        "apple-id-recovery.xyz", "apple-store-verify.com", "apple-id-unlock.top",
        "apple-billing-update.xyz", "apple-id-reset-password.com", "apple-confirm-purchase.top",
        "apple-device-verify.xyz", "apple-find-my-verify.com", "apple-subscription-update.top",
        "apple-id-phishing.xyz", "apple-login-verify.com", "apple-security-center.top",
        "apple-id-update-info.xyz", "apple-account-locked.com", "apple-payment-failed.top",
        "apple-id-verify-now.xyz", "apple-icloud-verify.com", "apple-id-secure-login.top",
        "apple-confirm-identity.xyz", "apple-id-review.com", "apple-account-alert.top",
        // ===== PHISHING — Microsoft =====
        "microsoft-account-verify.com", "microsoft-login-secure.xyz", "microsoft-365-verify.top",
        "microsoft-outlook-login.xyz", "microsoft-teams-verify.com", "microsoft-onedrive-login.top",
        "microsoft-security-alert.xyz", "microsoft-account-locked.com", "microsoft-password-reset.top",
        "microsoft-azure-login.xyz", "microsoft-office-verify.com", "microsoft-sharepoint-login.top",
        "microsoft-windows-update.xyz", "microsoft-verify-now.com", "microsoft-account-review.top",
        "microsoft-support-center.xyz", "microsoft-billing-update.com", "microsoft-subscription-renew.top",
        "microsoft-confirm-identity.xyz", "microsoft-unusual-signin.com", "microsoft-secure-login.top",
        "microsft-login.xyz", "micros0ft-verify.com", "mlcrosoft-security.top",
        "micosoft-account.xyz", "microsoftt-login.com", "microsoft-0ffice.top",
        "microsoft-365-login.xyz", "microsoft-defender-alert.com", "microsoft-edge-update.top",
        // ===== PHISHING — Google =====
        "google-account-security.com", "g00gle-security.com", "google-verify-login.xyz",
        "google-account-locked.top", "google-drive-share.xyz", "google-gmail-verify.com",
        "google-photos-share.top", "google-play-verify.xyz", "google-chrome-update.com",
        "google-maps-verify.top", "google-meet-login.xyz", "google-workspace-verify.com",
        "google-adsense-login.top", "google-analytics-verify.xyz", "google-cloud-login.com",
        "google-support-center.top", "googl3-security.xyz", "go0gle-account.com",
        "google-verify-identity.top", "google-password-reset.xyz", "google-unusual-activity.com",
        "google-secure-login.top", "google-confirm-identity.xyz", "google-billing-update.com",
        "google-subscription-alert.top", "google-recovery-page.xyz", "google-sign-in-verify.com",
        "google-apps-verify.top", "google-youtube-login.xyz", "google-authenticator-setup.com",
        // ===== PHISHING — Amazon =====
        "amazon-order-verify.com", "amaz0n-verify.com", "amazon-prime-verify.xyz",
        "amazon-security-alert.top", "amazon-delivery-update.xyz", "amazon-account-locked.com",
        "amazon-billing-update.top", "amazon-payment-failed.xyz", "amazon-seller-verify.com",
        "amazon-alexa-setup.top", "amazon-aws-login.xyz", "amazon-kindle-verify.com",
        "amazon-warehouse-deal.top", "amazon-refund-claim.xyz", "amazon-prime-renew.com",
        "amazon-gift-card-free.top", "amazon-customer-support.xyz", "amazon-order-cancel.com",
        "amazon-account-review.top", "amazon-subscription-update.xyz", "amazon-signin-verify.com",
        "amazn-login.top", "arnazon-verify.xyz", "amaz0n-prime.com",
        "amazon-secure-signin.top", "amazon-confirm-order.xyz", "amazon-shipping-update.com",
        "amazon-wishlist-share.top", "amazon-return-request.xyz", "amazon-credit-card-update.com",
        // ===== PHISHING — Netflix =====
        "netflix-billing-update.com", "netflix-login-verify.xyz", "netflix-account-locked.top",
        "netflix-payment-failed.xyz", "netflix-subscription-renew.com", "netflix-verify-account.top",
        "netflix-security-alert.xyz", "netflix-password-reset.com", "netflix-update-payment.top",
        "netflix-free-trial.xyz", "netflix-confirm-identity.com", "netflix-unusual-activity.top",
        "netflix-support-center.xyz", "netflix-billing-issue.com", "netflix-account-review.top",
        "netflix-verify-now.xyz", "netfllx-login.com", "netfl1x-verify.top",
        "netflix-premium-free.xyz", "netflix-gift-card.com", "netflix-secure-login.top",
        "netflix-update-info.xyz", "netflix-reactivate.com", "netflix-signup-free.top",
        // ===== PHISHING — Banking =====
        "bank-secure-login.com", "secure-banking-login.xyz", "chase-verify-account.top",
        "wellsfargo-login-secure.xyz", "bankofamerica-verify.com", "citibank-login-secure.top",
        "hsbc-verify-account.xyz", "barclays-secure-login.com", "capitalone-verify.top",
        "usbank-login-secure.xyz", "td-bank-verify.com", "pnc-secure-login.top",
        "suntrust-verify-account.xyz", "regions-bank-login.com", "ally-bank-verify.top",
        "discover-login-secure.xyz", "schwab-verify-account.com", "fidelity-secure-login.top",
        "vanguard-verify.xyz", "merrill-lynch-login.com", "goldman-sachs-verify.top",
        "morgan-stanley-login.xyz", "boa-secure-verify.com", "chase-card-verify.top",
        "amex-login-verify.xyz", "visa-secure-verify.com", "mastercard-verify.top",
        "venmo-verify-account.xyz", "zelle-payment-verify.com", "cashapp-verify-login.top",
        // ===== PHISHING — Social Media =====
        "facebook-security-check.com", "instagram-verify-account.com", "twitter-login-verify.xyz",
        "tiktok-verify-account.top", "snapchat-login-secure.xyz", "linkedin-verify.com",
        "whatsapp-verify-code.com", "telegram-login-verify.top", "discord-verify-account.xyz",
        "reddit-login-secure.com", "pinterest-verify.top", "tumblr-login-secure.xyz",
        "facebook-confirm-identity.com", "instagram-security-alert.top", "twitter-unusual-activity.xyz",
        "tiktok-account-locked.com", "snapchat-verify-now.top", "linkedin-account-review.xyz",
        "whatsapp-update-app.com", "telegram-security-alert.top", "discord-nitro-free.xyz",
        "facebook-page-verify.com", "instagram-business-verify.top", "twitter-badge-verify.xyz",
        "faceb00k-login.com", "lnstagram-verify.top", "tw1tter-login.xyz",
        "t1ktok-verify.com", "l1nkedin-login.top", "wh4tsapp-verify.xyz",
        // ===== PHISHING — Telecom =====
        "att-verify-account.xyz", "verizon-login-secure.top", "tmobile-verify.xyz",
        "sprint-account-verify.com", "comcast-billing-update.top", "spectrum-login-secure.xyz",
        "cox-verify-account.com", "directv-billing-update.top", "dish-network-verify.xyz",
        "atandt-payment-update.com", "verizon-fios-verify.top", "xfinity-login-secure.xyz",
        // ===== PHISHING — Government =====
        "government-payment-portal.com", "irs-refund-claim.xyz", "tax-refund-claim.com",
        "ssa-benefit-update.top", "medicare-verify.xyz", "dmv-renewal-online.com",
        "usps-delivery-update.top", "fedex-tracking-update.xyz", "ups-delivery-verify.com",
        "dhl-shipment-update.top", "customs-payment-required.xyz", "immigration-visa-update.com",
        "irs-payment-portal.top", "state-tax-refund.xyz", "unemployment-benefit-claim.com",
        "stimulus-check-claim.top", "covid-vaccine-register.xyz", "pandemic-relief-payment.com",
        // ===== MALWARE C2 — Trojan =====
        "malware-c2-server1.xyz", "botnet-control-panel.top", "trojan-download-server.club",
        "banking-trojan-c2.biz", "rat-command-server.net", "credential-stealer-api.xyz",
        "exploit-kit-landing.top", "android-malware-c2.top", "mobile-rat-server.xyz",
        "banking-overlay-c2.com", "sms-stealer-server.net", "clipboard-hijack-c2.org",
        "screenlogger-server.com", "permission-abuse-c2.net", "fake-vpn-data-steal.com",
        "adware-click-fraud.xyz", "ransomware-android.xyz", "joker-malware-c2.top",
        "harly-trojan-c2.xyz", "facestealer-c2.com", "anatsa-banker-c2.top",
        "sharkbot-c2-server.xyz", "vultur-bankbot-c2.com", "octo-banker-c2.top",
        "hydra-trojan-c2.xyz", "ermac-banker-c2.com", "hook-banker-c2.top",
        "cerberus-c2-server.xyz", "anubis-banker-c2.com", "eventbot-c2.top",
        "teabot-c2-server.xyz", "flubot-c2-domain.com", "medusa-banker-c2.top",
        "xenomorph-c2.xyz", "godfather-trojan-c2.com", "nexus-banker-c2.top",
        "brata-trojan-c2.xyz", "coper-banker-c2.com", "sova-trojan-c2.top",
        // ===== MALWARE C2 — Generated =====
        "a8f3k2.xyz", "b7g4m1.top", "c6h5n3.club", "d9j2p4.buzz", "e3k7q5.work",
        "f1l8r6.click", "g4m9s7.icu", "h2n5t8.monster", "i6o3u1.xyz", "j8p4v2.top",
        "k1q6w3.club", "l3r7x5.buzz", "m5s8y4.work", "n7t2z6.click", "o9u4a1.icu",
        "p2v5b3.monster", "q4w6c8.xyz", "r6x1d7.top", "s8y3e5.club", "t1z4f2.buzz",
        "u3a6g9.work", "v5b7h1.click", "w7c8i3.icu", "x9d2j5.monster", "y2e4k7.xyz",
        "z4f6l9.top", "a1g3m2.club", "b8h5n4.buzz", "c3i7o6.work", "d5j9p8.click",
        "e7k2q1.icu", "f9l4r3.monster", "g2m6s5.xyz", "h4n8t7.top", "i6o1u9.club",
        "j8p3v2.buzz", "k1q5w4.work", "l3r7x6.click", "m5s9y8.icu", "n7t2z1.monster",
        "xn--pple-43d.com", "xn--ggle-55da.com", "xn--amzon-j1a.com", "xn--fcbook-bsa.com",
        "xn--ntflx-p1a.com", "xn--pypal-4na.com", "xn--mcrsft-n1a.com", "xn--chse-n1a.com",
        "xn--brkly-y1a.com", "xn--wllsfrg-y4a.com",
        // ===== MALWARE C2 — Botnets =====
        "bot-cmd-relay1.xyz", "bot-cmd-relay2.top", "bot-cmd-relay3.club",
        "botnet-proxy-gate.buzz", "botnet-dropper.work", "botnet-loader.click",
        "ddos-botnet-c2.icu", "spam-botnet-c2.monster", "crypto-botnet-c2.xyz",
        "iot-botnet-c2.top", "mirai-variant-c2.club", "mozi-botnet-c2.buzz",
        "emotet-epoch1-c2.work", "emotet-epoch2-c2.click", "emotet-epoch3-c2.icu",
        "trickbot-c2-gate.monster", "qakbot-c2-proxy.xyz", "icedid-c2-relay.top",
        "bumblebee-c2.club", "pikabot-c2-gate.buzz", "darkgate-c2.work",
        "asyncrat-c2.click", "remcos-c2-server.icu", "nanocore-c2.monster",
        "njrat-c2-relay.xyz", "warzone-rat-c2.top", "quasar-rat-c2.club",
        "orcus-rat-c2.buzz", "lime-rat-c2.work", "dcrat-c2-server.click",
        // ===== MALWARE C2 — Ransomware =====
        "ransomware-payment.onion.ws", "lockbit-payment.xyz", "blackcat-leak.top",
        "royal-ransom-pay.club", "clop-data-leak.buzz", "medusa-locker.work",
        "black-basta-pay.click", "hive-ransom-portal.icu", "conti-leak-site.monster",
        "revil-mirror.xyz", "darkside-pay.top", "ransomexx-leak.club",
        "avoslocker-pay.buzz", "vice-society-leak.work", "bianlian-extort.click",
        "play-ransom-leak.icu", "akira-ransom-pay.monster", "rhysida-leak.xyz",
        "cactus-ransom-pay.top", "hunters-intl-leak.club",
        // ===== MALWARE — Dropper/Loader =====
        "apk-dropper-stage1.xyz", "apk-dropper-stage2.top", "payload-delivery.club",
        "malware-stage-host.buzz", "exploit-payload.work", "drive-by-loader.click",
        "fileless-loader.icu", "in-memory-payload.monster", "dll-sideload.xyz",
        "shellcode-host.top", "cobalt-strike-c2.club", "metasploit-payload.buzz",
        "meterpreter-c2.work", "havoc-c2-server.click", "sliver-c2-implant.icu",
        "brute-ratel-c2.monster", "mythic-c2-agent.xyz", "covenant-c2.top",
        // ===== SPYWARE/STALKERWARE =====
        "spyware-install.com", "phone-spy-tracker.com", "hidden-recorder-app.com",
        "stealth-monitor.net", "remote-access-tool.xyz", "spy-on-phone.xyz",
        "track-my-partner.top", "hidden-phone-tracker.club", "stealth-spy-app.buzz",
        "invisible-tracker.work", "phone-monitor-hidden.click", "secret-recorder.icu",
        "call-recorder-stealth.monster", "sms-spy-hidden.xyz", "location-spy-app.top",
        "camera-spy-remote.club", "microphone-spy.buzz", "keylogger-android.work",
        "screen-capture-spy.click", "whatsapp-spy-tool.icu", "instagram-spy-app.monster",
        "facebook-spy-tool.xyz", "snapchat-spy.top", "tiktok-spy-app.club",
        "partner-tracker.buzz", "child-spy-hidden.work", "employee-spy-stealth.click",
        "gps-tracker-hidden.icu", "stalkerware-install.monster", "spy-phone-app.xyz",
        "mspy-alternative.top", "flexispy-download.club", "cocospy-install.buzz",
        "spyic-download.work", "umobix-install.click", "hoverwatch-download.icu",
        "eyezy-install.monster", "moniterro-download.xyz", "xnspy-install.top",
        // ===== SCAM — Tech Support =====
        "tech-support-scam.com", "microsoft-support-scam.xyz", "apple-support-scam.top",
        "google-support-scam.club", "windows-virus-alert.buzz", "your-pc-infected.work",
        "critical-security-warning.click", "virus-detected-alert.icu", "malware-found-scan.monster",
        "computer-locked-call.xyz", "browser-hijack-alert.top", "driver-update-needed.club",
        "system-error-fix.buzz", "registry-cleaner-scan.work", "pc-optimizer-scam.click",
        "antivirus-expired-renew.icu", "firewall-breached-alert.monster", "data-breach-notify.xyz",
        "identity-theft-alert.top", "credit-monitoring-scam.club",
        // ===== SCAM — Prize/Lottery =====
        "scam-prize-winner.com", "lottery-winner-claim.com", "congratulations-winner.xyz",
        "you-won-iphone.top", "free-gift-card-claim.club", "survey-rewards-claim.buzz",
        "lucky-draw-winner.work", "exclusive-prize-draw.click", "million-dollar-winner.icu",
        "sweepstakes-winner.monster", "claim-your-prize.xyz", "raffle-winner-notify.top",
        "jackpot-winner-claim.club", "casino-bonus-claim.buzz", "spin-to-win-free.work",
        "free-vacation-winner.click", "car-giveaway-winner.icu", "electronics-giveaway.monster",
        "amazon-gift-card-free.xyz", "walmart-gift-card-free.top",
        // ===== SCAM — Romance/Social =====
        "meet-singles-now.xyz", "dating-verification.top", "romance-verify-profile.club",
        "military-romance-scam.buzz", "sugar-daddy-scam.work", "inheritance-claim.click",
        "nigerian-prince-offer.icu", "business-proposal-urgent.monster", "charity-donation-scam.xyz",
        "emergency-fund-request.top", "stranded-traveler-help.club", "sick-relative-fund.buzz",
        "investment-guru-secret.work", "work-from-home-easy.click", "get-rich-quick.icu",
        "forex-profit-guaranteed.monster", "binary-options-profit.xyz", "mlm-opportunity.top",
        // ===== SCAM — E-commerce =====
        "fake-shop-deals.xyz", "replica-designer-store.top", "discount-electronics-90off.club",
        "cheap-iphone-sale.buzz", "luxury-bags-outlet.work", "branded-shoes-cheap.click",
        "wholesale-electronics.icu", "clearance-sale-today.monster", "flash-sale-exclusive.xyz",
        "too-good-to-be-true.top", "unbelievable-deals.club", "super-discount-store.buzz",
        "fake-amazon-seller.work", "counterfeit-goods-shop.click", "scam-online-store.icu",
        "phishing-checkout.monster", "steal-card-checkout.xyz", "fake-payment-gateway.top",
        // ===== CRYPTOCURRENCY SCAM =====
        "free-bitcoin-generator.com", "crypto-airdrop-claim.xyz", "nft-mint-exclusive.com",
        "defi-yield-farm.xyz", "token-presale-exclusive.com", "free-eth-airdrop.xyz",
        "btc-double-now.com", "crypto-wallet-verify.com", "blockchain-verify-wallet.com",
        "bitcoin-doubler.top", "ethereum-giveaway.club", "solana-airdrop-free.buzz",
        "cardano-staking-bonus.work", "polkadot-presale.click", "avalanche-airdrop.icu",
        "dogecoin-generator.monster", "shiba-inu-airdrop.xyz", "binance-bonus-claim.top",
        "coinbase-verify-account.club", "kraken-login-verify.buzz", "metamask-verify-wallet.work",
        "trustwallet-verify.click", "phantom-wallet-verify.icu", "uniswap-airdrop.monster",
        "pancakeswap-bonus.xyz", "opensea-verify-nft.top", "rarible-airdrop.club",
        "crypto-pump-signal.buzz", "guaranteed-profit-crypto.work", "insider-crypto-tip.click",
        "mining-pool-bonus.icu", "cloud-mining-profit.monster", "hash-power-free.xyz",
        "bitcoin-mining-app.top", "eth-mining-free.club", "crypto-investment-plan.buzz",
        "yield-farming-profit.work", "defi-staking-bonus.click", "liquidity-pool-scam.icu",
        "rug-pull-token.monster", "pump-dump-coin.xyz", "fake-ico-presale.top",
        "ponzi-crypto-scheme.club", "pyramid-token.buzz", "crypto-recovery-scam.work",
        "wallet-recovery-service.click", "seed-phrase-verify.icu", "private-key-verify.monster",
        // ===== CRYPTOJACKING/MINING =====
        "coinhive-miner.xyz", "cryptonight-pool.top", "browser-miner.club",
        "webminer-proxy.buzz", "monero-miner-js.work", "crypto-miner-hidden.click",
        "wasm-miner.icu", "webassembly-miner.monster", "coinimp-miner.xyz",
        "cryptoloot-pool.top", "mineralt-proxy.club", "jsecoin-miner.buzz",
        "coin-have-miner.work", "deep-miner-proxy.click", "perfekt-miner.icu",
        "crypto-webminer.monster", "browser-mine-pool.xyz", "silent-miner-js.top",
        "background-miner.club", "hidden-crypto-mine.buzz", "stealth-miner.work",
        "android-miner-hidden.click", "mobile-crypto-mine.icu", "cpu-miner-stealth.monster",
        "gpu-miner-web.xyz", "mining-script-host.top", "inject-miner.club",
        "xmr-pool-proxy.buzz", "randomx-miner.work", "kawpow-miner.click",
        "ethash-miner.icu", "autolykos-miner.monster", "equihash-miner.xyz",
        "mining-proxy-relay.top", "stratum-proxy-mine.club", "pool-relay-miner.buzz",
        "hashrate-booster.work", "overclock-miner.click", "turbo-mine-crypto.icu",
        "free-mining-power.monster", "instant-mining.xyz", "mega-hash-miner.top",
        "ultra-mine-profit.club", "quick-mine-btc.buzz", "fast-mine-eth.work",
        "rapid-mine-xmr.click", "super-mine-crypto.icu", "power-mine-coin.monster",
        // ===== FAKE APP STORES =====
        "free-premium-apps.com", "modded-apk-download.com", "cracked-apps-store.com",
        "free-games-download.xyz", "premium-apps-free.com", "paid-apps-free.xyz",
        "apk-mod-download.top", "cracked-games-android.club", "hack-games-apk.buzz",
        "unlimited-coins-mod.work", "god-mode-apk.click", "cheat-engine-mobile.icu",
        "game-hack-android.monster", "apk-mirror-fake.xyz", "google-play-mod.top",
        "app-store-cracked.club", "ipa-download-free.buzz", "tweaked-apps-ios.work",
        "sideload-apps-free.click", "jailbreak-apps.icu", "root-apps-download.monster",
        "lucky-patcher-download.xyz", "game-guardian-apk.top", "creehack-download.club",
        "freedom-apk-download.buzz", "sb-game-hacker.work", "xmod-games.click",
        "mod-apk-store.icu", "apk-pure-fake.monster", "apk-combo-fake.xyz",
        // ===== FAKE UPDATES/DOWNLOADS =====
        "fake-update-download.com", "chrome-update-now.xyz", "firefox-update-urgent.top",
        "flash-player-update.club", "java-update-required.buzz", "adobe-reader-update.work",
        "windows-update-now.click", "macos-update-critical.icu", "android-update-available.monster",
        "ios-update-now.xyz", "browser-update-needed.top", "plugin-update-required.club",
        "codec-pack-download.buzz", "video-player-update.work", "media-player-codec.click",
        "font-pack-required.icu", "driver-update-tool.monster", "bios-update-utility.xyz",
        "firmware-update-tool.top", "system-update-android.club",
        // ===== EXPLOIT KITS =====
        "exploit-kit-rig.top", "drive-by-download.xyz", "browser-exploit-pack.com",
        "zero-day-exploit.biz", "vulnerability-scanner.xyz", "exploit-kit-magnitude.top",
        "exploit-kit-fallout.club", "exploit-kit-spelevo.buzz", "exploit-kit-underminer.work",
        "exploit-kit-purplefox.click", "exploit-kit-bottle.icu", "exploit-kit-lord.monster",
        "exploit-landing-page.xyz", "exploit-redirect.top", "malvertising-landing.club",
        "drive-by-exploit.buzz", "watering-hole-site.work", "typosquat-exploit.click",
        "seo-poison-landing.icu", "search-hijack-redirect.monster",
        // ===== ADWARE/MALVERTISING =====
        "track-user-activity.com", "device-fingerprint-api.com", "location-tracker-sdk.com",
        "silent-push-service.com", "background-data-collect.com", "aggressive-popup-ad.xyz",
        "fullscreen-ad-overlay.top", "interstitial-ad-spam.club", "notification-ad-spam.buzz",
        "push-notification-ad.work", "browser-redirect-ad.click", "search-hijack-ad.icu",
        "homepage-hijack-ad.monster", "toolbar-install-ad.xyz", "browser-extension-ad.top",
        "ad-injection-proxy.club", "click-fraud-network.buzz", "impression-fraud.work",
        "ad-stacking-fraud.click", "pixel-stuffing-fraud.icu",
        // ===== SMS/OTP FRAUD =====
        "sms-verification-service.com", "otp-bypass-service.com", "phone-number-verify.com",
        "sms-intercept-service.xyz", "otp-steal-relay.top", "sms-forwarding-service.club",
        "virtual-number-otp.buzz", "disposable-sms-receive.work", "temp-phone-number.click",
        "receive-sms-online.icu", "sms-code-intercept.monster", "otp-grabber-service.xyz",
        "sim-swap-service.top", "call-forwarding-hack.club", "voicemail-hack.buzz",
        "pin-bypass-service.work", "2fa-bypass-tool.click", "mfa-bypass-service.icu",
        // ===== FAKE ANTIVIRUS =====
        "fake-antivirus-alert.com", "your-phone-infected.xyz", "virus-scan-online.top",
        "remove-virus-now.club", "security-scan-free.buzz", "antivirus-download-free.work",
        "malware-removal-tool.click", "spyware-cleaner-free.icu", "adware-remover.monster",
        "trojan-scanner-free.xyz", "rootkit-detector-free.top", "ransomware-decryptor.club",
        "fake-mcafee-alert.buzz", "fake-norton-scan.work", "fake-avast-warning.click",
        "fake-kaspersky-alert.icu", "fake-bitdefender.monster", "fake-malwarebytes.xyz",
        "fake-windows-defender.top", "fake-google-play-protect.club",
        // ===== CREDENTIAL HARVESTING =====
        "login-portal-secure.xyz", "webmail-login-verify.top", "cpanel-login-secure.club",
        "wordpress-admin-login.buzz", "phpmyadmin-login.work", "ftp-login-portal.click",
        "ssh-key-verify.icu", "vpn-login-portal.monster", "remote-desktop-login.xyz",
        "citrix-gateway-login.top", "okta-verify-login.club", "duo-security-verify.buzz",
        "auth0-login-verify.work", "saml-login-portal.click", "oauth-verify-token.icu",
        "jwt-token-verify.monster", "api-key-verify.xyz", "webhook-verify.top",
        // ===== DELIVERY SCAM =====
        "delivery-tracking-update.com", "usps-delivery-reschedule.xyz", "fedex-package-held.top",
        "ups-customs-payment.club", "dhl-delivery-failed.buzz", "royal-mail-redelivery.work",
        "amazon-delivery-issue.click", "walmart-delivery-update.icu", "target-order-issue.monster",
        "costco-delivery-update.xyz", "bestbuy-order-update.top", "ebay-shipping-issue.club",
        "aliexpress-customs.buzz", "wish-delivery-update.work", "shein-order-issue.click",
        "temu-delivery-update.icu", "etsy-shipping-issue.monster",
        // ===== SURVEY/REWARD SCAM =====
        "complete-survey-reward.xyz", "opinion-reward-claim.top", "gift-card-survey.club",
        "paid-survey-online.buzz", "cash-reward-survey.work", "free-product-test.click",
        "brand-ambassador-apply.icu", "product-tester-wanted.monster", "market-research-pay.xyz",
        "focus-group-online-pay.top", "mystery-shopper-apply.club", "review-products-pay.buzz",
        "user-testing-reward.work", "app-testing-reward.click", "beta-test-reward.icu",
        "referral-bonus-claim.monster",
        // ===== MALICIOUS REDIRECTORS =====
        "short-url-malware.xyz", "url-redirect-malicious.top", "click-tracker-malware.club",
        "link-shortener-malware.buzz", "redirect-chain.work", "traffic-distribution.click",
        "tds-redirect.icu", "cloaked-redirect.monster", "geo-redirect-malware.xyz",
        "conditional-redirect.top", "fingerprint-redirect.club", "ab-test-malware.buzz",
        "split-test-redirect.work", "rotate-landing.click", "randomize-destination.icu",
        "traffic-broker.monster",
        // ===== FAKE LOGIN PAGES =====
        "secure-login-verify.com", "account-verify-update.com", "login-secure-update.net",
        "confirm-identity-now.com", "account-suspended-verify.com", "unusual-activity-alert.com",
        "security-alert-action.com", "payment-failed-update.com", "verify-your-account.top",
        "login-verify-secure.xyz", "account-confirm-now.top", "identity-verify-login.club",
        "secure-signin-portal.buzz", "authentication-required.work", "credential-verify.click",
        "password-expire-alert.icu", "account-recovery-portal.monster", "2fa-setup-verify.xyz",
        "security-question-verify.top", "backup-email-verify.club",
        // ===== DATA EXFILTRATION =====
        "spyware-exfil-data.info", "keylogger-data-collect.org", "data-exfil-relay.xyz",
        "stolen-data-dump.top", "credential-dump-host.club", "database-leak-host.buzz",
        "data-broker-dark.work", "personal-info-sell.click", "identity-data-market.icu",
        "credit-card-dump.monster", "fullz-shop.xyz", "cvv-store.top",
        "dumps-and-pins.club", "carding-forum.buzz", "fraud-tools-shop.work",
        "phishing-kit-store.click", "exploit-market.icu", "zero-day-shop.monster",
        // ===== ADDITIONAL PHISHING PATTERNS =====
        "dropbox-share-verify.xyz", "onedrive-share-verify.top", "google-drive-verify.club",
        "icloud-storage-full.buzz", "wetransfer-download.work", "sharepoint-access.click",
        "slack-workspace-verify.icu", "zoom-meeting-verify.monster", "webex-join-verify.xyz",
        "teams-meeting-verify.top", "skype-verify-account.club", "signal-verify-code.buzz",
        "protonmail-verify.work", "tutanota-login.click", "fastmail-verify.icu",
        "aol-mail-verify.monster", "yahoo-mail-verify.xyz", "outlook-verify-login.top",
        "gmail-verify-account.club", "icloud-mail-verify.buzz",
        // ===== ADDITIONAL MALWARE TLDs =====
        "secure-payment-process.xyz", "online-banking-portal.top", "customer-support-chat.club",
        "technical-support-team.buzz", "account-management-portal.work", "service-desk-portal.click",
        "helpdesk-support-center.icu", "billing-department-portal.monster",
        "account-verification-center.xyz", "identity-protection-service.top",
        "fraud-prevention-center.club", "security-monitoring-portal.buzz",
        "threat-detection-service.work", "incident-response-portal.click",
        "compliance-verification.icu", "audit-notification-portal.monster",
        "regulatory-compliance.xyz", "policy-update-notification.top",
        "terms-update-review.club", "privacy-policy-update.buzz",
        // ===== FAKE STREAMING =====
        "free-movie-stream.xyz", "watch-online-free.top", "hd-stream-movies.club",
        "premium-stream-free.buzz", "netflix-free-account.work", "disney-plus-free.click",
        "hbo-max-free-trial.icu", "paramount-plus-free.monster", "hulu-free-stream.xyz",
        "amazon-prime-free.top", "peacock-free-stream.club", "apple-tv-free.buzz",
        "sports-stream-live.work", "football-stream-free.click", "nba-stream-live.icu",
        "nfl-stream-free.monster", "ufc-fight-stream.xyz", "boxing-stream-live.top",
        "cricket-stream-free.club", "f1-stream-live.buzz",
        // ===== FAKE GAMING =====
        "free-vbucks-generator.xyz", "robux-generator-free.top", "minecraft-free-download.club",
        "fortnite-hack-aimbot.buzz", "apex-legends-hack.work", "cod-warzone-hack.click",
        "gta-money-glitch.icu", "among-us-hack.monster", "roblox-hack-robux.xyz",
        "valorant-hack-free.top", "csgo-cheats-free.club", "pubg-hack-uc.buzz",
        "league-of-legends-hack.work", "dota2-mmr-boost.click", "overwatch-aimbot.icu",
        "genshin-primogems-free.monster", "pokemon-go-spoof.xyz", "clash-royale-gems.top",
        "candy-crush-lives.club", "coin-master-spins.buzz",
        // ===== FAKE VPN/PROXY =====
        "free-vpn-unlimited.xyz", "fast-vpn-free.top", "secure-vpn-free.club",
        "private-vpn-free.buzz", "anonymous-vpn-free.work", "no-log-vpn-free.click",
        "military-grade-vpn.icu", "unblock-everything-vpn.monster", "stream-vpn-free.xyz",
        "torrent-vpn-free.top", "proxy-unblock-free.club", "web-proxy-anonymous.buzz",
        "socks5-proxy-free.work", "http-proxy-list.click", "vpn-crack-download.icu",
        "premium-vpn-free.monster", "vpn-mod-apk.xyz", "express-vpn-crack.top",
        "nord-vpn-free-account.club", "surfshark-crack.buzz",
        // ===== FAKE TOOLS/UTILITIES =====
        "wifi-password-hack.xyz", "wifi-hacker-tool.top", "instagram-password-hack.club",
        "facebook-hack-tool.buzz", "snapchat-hack-free.work", "whatsapp-hack-tool.click",
        "phone-number-lookup.icu", "reverse-phone-free.monster", "email-lookup-free.xyz",
        "ip-address-tracker.top", "location-tracker-phone.club", "spy-camera-detector.buzz",
        "hidden-camera-finder.work", "bug-detector-app.click", "signal-jammer-app.icu",
        "call-recorder-free.monster", "screen-recorder-pro.xyz", "photo-recovery-free.top",
        "data-recovery-tool.club", "file-recovery-free.buzz",
        // ===== ADDITIONAL PHISHING — Retail =====
        "walmart-gift-card.xyz", "target-survey-reward.top", "costco-membership-verify.club",
        "bestbuy-order-confirm.buzz", "homedepot-survey.work", "lowes-gift-card.click",
        "macys-sale-exclusive.icu", "nordstrom-gift-card.monster", "kohls-cash-bonus.xyz",
        "sephora-gift-card.top", "ulta-beauty-reward.club", "gap-sale-exclusive.buzz",
        "old-navy-gift-card.work", "bath-body-works-coupon.click", "victoria-secret-reward.icu",
        "nike-clearance-90off.monster", "adidas-discount-code.xyz", "puma-flash-sale.top",
        "under-armour-outlet.club", "lululemon-sale.buzz",
        // ===== ADDITIONAL PHISHING — Food/Delivery =====
        "doordash-free-delivery.xyz", "ubereats-credit-free.top", "grubhub-gift-card.club",
        "instacart-promo-code.buzz", "postmates-free-delivery.work", "seamless-credit.click",
        "chipotle-free-burrito.icu", "starbucks-gift-card-free.monster", "mcdonalds-free-meal.xyz",
        "subway-free-sub.top", "dominos-free-pizza.club", "pizza-hut-deal.buzz",
        "burger-king-free.work", "wendys-free-meal.click", "taco-bell-deal.icu",
        "dunkin-gift-card.monster", "chick-fil-a-free.xyz", "panera-gift-card.top",
        // ===== ADDITIONAL PHISHING — Travel =====
        "airline-ticket-free.xyz", "free-flight-booking.top", "hotel-booking-scam.club",
        "airbnb-verify-host.buzz", "booking-com-verify.work", "expedia-refund-claim.click",
        "trivago-exclusive-deal.icu", "kayak-special-offer.monster", "priceline-mega-deal.xyz",
        "hotels-com-reward.top", "southwest-free-flight.club", "delta-miles-bonus.buzz",
        "united-miles-double.work", "american-airlines-upgrade.click", "jetblue-free-ticket.icu",
        "spirit-airlines-refund.monster", "frontier-miles-bonus.xyz", "allegiant-free-flight.top",
        // ===== ADDITIONAL INFRASTRUCTURE =====
        "bulletproof-hosting.xyz", "offshore-hosting.top", "anonymous-hosting.club",
        "no-abuse-hosting.buzz", "dark-web-hosting.work", "tor-hidden-service.click",
        "i2p-hosting.icu", "freenet-hosting.monster", "vpn-hosting-anon.xyz",
        "proxy-hosting-anon.top", "cdn-malware-host.club", "fast-flux-dns.buzz",
        "domain-fronting.work", "dns-tunneling.click", "icmp-tunneling.icu",
        "covert-channel.monster", "steganography-host.xyz", "dead-drop-dns.top",
        "dga-domain-gen.club", "algorithm-generated.buzz",
        // ===== ADDITIONAL RANDOM GENERATED DOMAINS =====
        "qwerty-asdf.xyz", "zxcvb-mnbv.top", "poiuy-trewq.club",
        "lkjhg-fdsa.buzz", "mnbvc-xzasd.work", "qazwsx-edc.click",
        "rfvtgb-yhn.icu", "ujmik-olp.monster", "plokij-uhyg.xyz",
        "tfrde-swaq.top", "zaqxsw-cde.club", "vfrbgt-nhy.buzz",
        "mju7y-h6tg.work", "bv5fc-r4dx.click", "se3za-w2q1.icu",
        "0p9o8-i7u6.monster", "y5t4r-3e2w.xyz", "1qaz2-wsx3.top",
        "edc4r-fv5t.club", "gb6yh-n7uj.buzz", "m8ik9-ol0p.work",
        "a1s2d-3f4g.click", "5h6j7-k8l9.icu", "z0x9c-8v7b.monster",
        "n6m5a-4s3d.xyz", "f2g1q-wert.top", "yuiop-asdf.club",
        "ghjkl-zxcv.buzz", "bnm12-3456.work", "78901-abcd.click",
        // ===== ADDITIONAL CREDENTIAL STEALERS =====
        "email-harvester.xyz", "password-stealer-kit.top", "credential-phishing.club",
        "form-grabber-c2.buzz", "browser-stealer-c2.work", "cookie-stealer-c2.click",
        "session-hijack-c2.icu", "token-stealer-c2.monster", "oauth-stealer.xyz",
        "saml-stealer.top", "kerberos-stealer.club", "ntlm-relay.buzz",
        "pass-the-hash.work", "golden-ticket.click", "silver-ticket.icu",
        "mimikatz-c2.monster", "lazagne-c2.xyz", "hashcat-cloud.top",
        "john-ripper-cloud.club", "bruteforce-service.buzz",
        // ===== ADDITIONAL FAKE SERVICES =====
        "free-followers-instagram.xyz", "buy-likes-cheap.top", "twitter-followers-free.club",
        "youtube-subscribers-free.buzz", "tiktok-followers-free.work", "facebook-likes-free.click",
        "social-media-bot.icu", "auto-like-service.monster", "engagement-boost-free.xyz",
        "viral-service-cheap.top", "seo-backlinks-free.club", "google-rank-first.buzz",
        "website-traffic-free.work", "click-farm-service.click", "review-farm.icu",
        "fake-reviews-cheap.monster", "astroturfing-service.xyz", "reputation-management.top",
        "remove-negative-reviews.club", "boost-app-ratings.buzz",
        // ===== ADDITIONAL PHISHING — Crypto Exchanges =====
        "binance-login-verify.xyz", "coinbase-verify-identity.top", "kraken-account-locked.club",
        "gemini-verify-account.buzz", "ftx-refund-claim.work", "crypto-com-verify.click",
        "kucoin-login-secure.icu", "bybit-verify-account.monster", "okx-login-verify.xyz",
        "bitfinex-verify.top", "bitstamp-login.club", "huobi-verify.buzz",
        "gate-io-verify.work", "mexc-login.click", "lbank-verify.icu",
        "bitget-login.monster", "phemex-verify.xyz", "deribit-login.top",
        "bitmex-verify.club", "poloniex-login.buzz",
        // ===== ADDITIONAL MALWARE — Android-specific =====
        "android-flashlight-spy.xyz", "calculator-vault-spy.top", "battery-saver-malware.club",
        "speed-booster-malware.buzz", "cleaner-master-fake.work", "antivirus-fake-android.click",
        "qr-scanner-malware.icu", "pdf-reader-malware.monster", "vpn-free-malware.xyz",
        "keyboard-malware.top", "weather-app-malware.club", "compass-app-malware.buzz",
        "flashlight-app-spy.work", "wallpaper-app-malware.click", "ringtone-app-malware.icu",
        "emoji-keyboard-spy.monster", "face-filter-malware.xyz", "photo-editor-malware.top",
        "music-player-malware.club", "video-player-malware.buzz",
        // ===== ADDITIONAL PHISHING — Health =====
        "pharmacy-online-cheap.xyz", "prescription-no-rx.top", "weight-loss-miracle.club",
        "diet-pills-free.buzz", "muscle-supplement-free.work", "health-insurance-quote.click",
        "medicare-supplement.icu", "dental-insurance-cheap.monster", "vision-insurance.xyz",
        "life-insurance-quote.top", "covid-test-free.club", "vaccine-appointment.buzz",
        "telehealth-free-visit.work", "online-doctor-free.click", "mental-health-free.icu",
        "therapy-online-free.monster",
        // ===== ADDITIONAL SCAM DOMAINS =====
        "work-from-home-job.xyz", "data-entry-job-online.top", "typing-job-from-home.club",
        "paid-online-surveys.buzz", "get-paid-to-click.work", "earn-money-watching-ads.click",
        "passive-income-easy.icu", "make-money-sleeping.monster", "financial-freedom-fast.xyz",
        "retire-early-secret.top", "debt-relief-program.club", "credit-repair-fast.buzz",
        "loan-approval-instant.work", "mortgage-refinance-low.click", "car-loan-approval.icu",
        "student-loan-forgive.monster", "grant-money-free.xyz", "government-grant-apply.top",
        "small-business-grant.club", "startup-funding-free.buzz",
        // ===== FILL TO 2500+ =====
        "secure-update-portal.xyz", "account-info-update.top", "verify-details-now.club",
        "confirm-account-info.buzz", "update-billing-info.work", "renew-subscription-now.click",
        "reactivate-account.icu", "restore-access-now.monster", "unlock-your-account.xyz",
        "remove-restriction.top", "appeal-decision.club", "review-pending-action.buzz",
        "action-required-now.work", "immediate-attention.click", "urgent-notice-action.icu",
        "final-warning-account.monster", "last-chance-verify.xyz", "deadline-approaching.top",
        "expiring-soon-renew.club", "limited-time-offer.buzz", "exclusive-deal-today.work",
        "flash-sale-ending.click", "clearance-final.icu", "members-only-deal.monster",
        "vip-exclusive-offer.xyz", "premium-upgrade-free.top", "trial-extended-free.club",
        "bonus-credit-added.buzz", "reward-points-expire.work", "loyalty-bonus-claim.click",
        "cashback-reward-claim.icu", "discount-code-exclusive.monster",
        "special-offer-inside.xyz", "announcement-important.top", "notification-alert.club",
        "system-notification.buzz", "automated-message.work", "no-reply-verify.click",
        "do-not-ignore.icu", "response-required.monster", "confirmation-needed.xyz",
        "approval-pending.top", "authorization-required.club", "validation-needed.buzz",
        "verification-code.work", "security-code-verify.click", "one-time-password.icu",
        "temporary-code.monster", "access-code-verify.xyz", "session-expired.top",
        "login-session-timeout.club", "re-authenticate.buzz", "credential-expired.work",
        "password-change-required.click", "mandatory-update.icu", "policy-violation.monster",
        "terms-violation-notice.xyz", "community-guidelines.top", "strike-warning.club",
        "copyright-claim.buzz", "dmca-notice.work", "trademark-violation.click",
        "legal-notice-urgent.icu", "cease-desist-notice.monster", "court-summons-online.xyz",
        "subpoena-notice.top", "warrant-notification.club", "fine-payment-portal.buzz",
        "penalty-payment.work", "overdue-payment-notice.click", "collection-agency.icu",
        "debt-collector-portal.monster", "invoice-payment-due.xyz", "statement-review.top",
        "receipt-confirmation.club", "transaction-declined.buzz", "payment-reversal.work",
        "chargeback-notification.click", "refund-processing.icu", "wire-transfer-confirm.monster",
        "ach-transfer-verify.xyz", "direct-deposit-update.top", "routing-number-verify.club",
        "swift-code-confirm.buzz", "beneficiary-update.work", "payee-verify.click",
        "remittance-details.icu", "money-transfer-confirm.monster"
    )

    fun isBlocked(domain: String): Boolean {
        val normalized = domain.lowercase().trim().removeSuffix(".")
        // Exact match
        if (normalized in domains) return true
        // Subdomain match (e.g., sub.evil.com matches evil.com)
        val parts = normalized.split(".")
        for (i in 1 until parts.size - 1) {
            val parent = parts.subList(i, parts.size).joinToString(".")
            if (parent in domains) return true
        }
        return false
    }

    fun addDomains(newDomains: Collection<String>) {
        domains.addAll(newDomains.map { it.lowercase().trim() })
    }

    fun getBlockedCount(): Int = domains.size
}
